name: E2E Test

on:
  push:

permissions:
  # デプロイ操作の許可
  deployments: write
  # アクションの操作の許可
  # # 主にArtifact
  actions: write
  # プルリクエストの操作の許可
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/totto2727-org/playwright-ja:v1.46.1
    env:
      LANG: ja_JP.UTF-8
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
      - name: Global Packages Install
        shell: bash
        run: npm i -g @antfu/ni
      - name: Packages Install
        shell: bash
        run: ni

      - name: Run Playwright
        run: na playwright test -u
        env:
          # Firefoxの問題を解決するための設定
          HOME: /root
